---

  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - build-essential
      - python-software-properties
      - vim
      - ruby

  - name: Update apt again
    sudo: yes
    apt:  update_cache=yes

  - name: Install extra packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items: sys_packages

  - stat: path=/etc/shorewall/rules
    register: shorewall_rules

  - name: Ruby change bashrc
    blockinfile:
      dest: "/home/{{ ansible_ssh_user }}/.bashrc"
      marker: "# {mark} RUBY GEM IN PATH"
      content: |
        if which ruby >/dev/null && which gem >/dev/null; then
            PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
        fi