---
  - name: Add webupd8team ppa (deb)
    sudo: yes
    shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list

  - name: Add webupd8team ppa (deb-src)
    sudo: yes
    shell: echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list

  - name: Add apt-key
    sudo: yes
    shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886

  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Accept Java 8 Licence
    shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
    args:
      creates: /etc/oracle-java-8-licence-acceptance

  - name: Install Oracle Java 8
    apt: name={{item}} state=latest
    sudo: yes
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default