---
  - name: Create aliases for SF
    blockinfile:
      dest: "/home/vagrant/.bashrc"
      marker: "# {mark} SYMFONY ALIASES"
      content: |
        alias sf='php app/console'
        alias pu='php vendor/bin/phpunit -c app/phpunit.xml'
        alias tu='php vendor/bin/phpunit -c app/phpunit.xml'
        alias tf='php vendor/bin/behat'

  - name: Clone SF completion
    sudo: no
    git: repo=https://github.com/jaytaph/SFConsole.git
         accept_hostkey=true
         dest=/home/vagrant/symfony-completion
         version=master

  - name: Change bashrc
    blockinfile:
      dest: "/home/vagrant/.bashrc"
      marker: "# {mark} SYMFONY AUTO COMPLETE"
      content: |
        if [ -f ~/symfony-completion/.console_completion.sh ]; then
          . ~/symfony-completion/.console_completion.sh
        fi