---
- hosts: production
  sudo:  true
  remote_user: admin
  vars:
    git_user_name: 'Vagrant'
    git_user_email: vagrant@mail.com
    doc_root: /var/www/web
    sys_packages:
      - mcrypt
    php_packages:
      - { name: dev, package: php5-dev }
      - { name: pear, package: php-pear }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: redis, package: php5-redis }
      - { name: imagick, package: php5-imagick }
      - { name: intl, package: php5-intl }
      - { name: apcu, package: php5-apcu }
    php_extensions:
      - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
    php_ppa: php5
  roles:
    - yaegashi.blockinfile
    - init
    - nginx
    - php5-fpm
    - php5-cli
    - php5-common
    - apc
    - composer
    - mysql
    - git
    - symfony
    - nodejs
    - curl
    - wget
    - redis
    - java8-oracle
    - frontend
