---
- hosts: all
  sudo:  true
  vars_prompt:
    - name: "git_user_name"
      prompt: "what is your GIT profile name?"
#      private: no
    - name: "git_user_email"
      prompt: "what is your GIT profile email?"
#      private: no
  vars:
    doc_root: /var/www/web
    sys_packages:
      - mcrypt
    php_packages:
      - { name: dev, package: php5-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: redis, package: php5-redis }
      - { name: memcached, package: php5-memcached }
      - { name: sqlite, package: php5-sqlite }
    php_extensions:
      - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
      - { name: "mongo", package: "pecl.php.net/mongo" }
      - { name: "xhprof", package: "pecl.php.net/xhprof-beta" }
    php_ppa: php5
  roles:
    - yaegashi.blockinfile
    - init
    - nginx
    - php5-fpm
    - php5-cli
    - php5-common
    - composer
    - phpunit
    - mysql
    - mongo
    - git
    - symfony
    - nodejs
    - capistrano
    - curl
    - sqlite
    - wget
#    - rabbitmq
    - redis
    - frontend
#    - memcached
